decompressed/gui_file/www/docroot/theme/Fritz/script.js
decompressed/gui_file/www/docroot/theme/Fritz/style.css

- Fixed openNav being called while in desktop view or when clicking a select Element
- (hopefully) a workaround for Safari not showing cards due to overflow property
- Fixed position of modal footer and header in Edge
- Fixed Internet Explorer not applying css with certain selector
- Fixed title not being centered
- Fixed sidemenu overflow

Bugfixes for Fritz Theme

---

decompressed/gui_file/www/docroot/gateway.lp
decompressed/gui_file/www/lang/de-de/webui-core.po
decompressed/gui_file/www/lua/cards_limiter.lua

Fixed some broken translations

---

README.md

Added the tg799 800 and 797n v3 root steps as well

Improve readme’s grammar punctuation and spelling

---

decompressed/base/etc/init.d/rootdevice
decompressed/gui_file/www/snippets/internet-pppoa-routed.lp
decompressed/gui_file/www/snippets/internet-pppoe-routed.lp

Allow to override PPPoE discovered DNS

---

decompressed/gui_file/www/docroot/modals/mmpbx-global-modal.lp
decompressed/gui_file/www/wizard-cards/002_voip.lp

Should really Fix https://github.com/Ansuel/tch-nginx-gui/issues/97

VoIP Realm and VoIP Proxy as Optional values

---

.github/ISSUE_TEMPLATE/bug.md

Fix grammar and spelling

---

decompressed/base/etc/init.d/rootdevice

See more here 
https://github.com/Ansuel/tch-nginx-gui/issues/161

Surpress ping error in rootdevice

---

decompressed/gui_file/www/docroot/modals/wireless-modal.lp

Is still a little glitchy ... when you turn on a radio you have to refresh the modal to get the Band Steering block, but at least now it appear.

Fix Band Steering

---

decompressed/gui_file/www/wizard-cards/001_broadband.lp

Clean the file as described here https://github.com/Ansuel/tch-nginx-gui/issues/118#issuecomment-418924722

Clean 001_broadband.lp and unmask PPP password

---

decompressed/gui_file/www/docroot/modals/gateway-modal.lp

change product name var hopefully it's populated on all devices
replaced Network Timezone checkbox with switch
should fix https://github.com/Ansuel/tch-nginx-gui/issues/124

Update Gateway modal

---

decompressed/gui_file/www/docroot/css/gw.css

fix https://github.com/Ansuel/tch-nginx-gui/issues/176

Fix style button over legend

---

decompresso/ base/ etc/ init.d/rootdevice

Should fix
https://github.com/Ansuel/tch-nginx-gui/issues/164
https://github.com/Ansuel/tch-nginx-gui/issues/118
and also 2 bug 
WAN DNS resetted on update (on some circumstance) 
pppoe relay tab show "invalid instance"

Update rootscript to set config placeholders

---

decompressed/gui_file/www/info-cards/004_xdsl_stats.lp

Add an xdsl stats card to the info view gui.
The CSS file needs to be fixed for this but i do not know how to do that :)

Create xdsl_stats card to view xdsl stats under stats menu

---

README.md

Fix grammar and wording.

---

decompressed/base/etc/init.d/rootdevice

Fix https://github.com/Ansuel/tch-nginx-gui/issues/123
And hopefully https://github.com/Ansuel/tch-nginx-gui/issues/155

Remove transformer ignored root pattern

---

decompressed/base/etc/init.d/rootdevice
decompressed/gui_file/www/snippets/internet-pppoa-routed.lp
decompressed/gui_file/www/snippets/internet-pppoe-routed.lp

Should also fix https://github.com/Ansuel/tch-nginx-gui/issues/118

Improve dns management better interface setup on rootdevice

---

decompressed/gui_file/www/docroot/modals/assistance-modal.lp

Fix https://github.com/Ansuel/tch-nginx-gui/issues/211

Fix remote assistance password set

---

decompressed/gui_file/www/cards/009_diagnostics.lp
decompressed/gui_file/www/cards/snippets/002_broadband_ethernet.lp
decompressed/gui_file/www/cards/snippets/002_broadband_xdsl.lp
decompressed/gui_file/www/docroot/modals/broadband-modal.lp
decompressed/gui_file/www/docroot/modals/ethernet-modal.lp
decompressed/gui_file/www/lua/broadbandmode_helper.lua
decompressed/gui_file/www/snippets/tabs-diagnostics.lp

sorry but code formatting completly messed the changes..

improve broadband switching

---

decompressed/gui_file/usr/share/transformer/mappings/rpc/sys.eth.map

As it should be!
Also in preparation for the Ports Status card

Change "BT" to "BASE-T" and "up" to "Up"

---

006_network.lp

Functional port reporting modal. Is a bit boring but I didn't have any ideas on how to spice it up :)

006_network_stats Card for Cards.lp

---

decompressed/gui_file/www/cards/009_extensions.lp

Rename “Applications” card to “Extensions”.

---

README.md

Also add installation of Telstra basic GUI into features list.

Update progress info about LuCI

---

decompressed/gui_file/www/info-cards/001_gateway.lp
decompressed/gui_file/www/info-cards/002_wanstats.lp
decompressed/gui_file/www/info-cards/006_xdsl_stats.lp

should also fix https://github.com/Ansuel/tch-nginx-gui/pull/230

strings and xdsl card fix

---

decompressed/gui_file/www/info-cards/005_mmpbxd_stats.lp

DECT Emission mode does not need to be enabled for DECT to work.
In my case (TG799vac) DECT can be enabled even with emission mode off.

DECT Emission Mode Cards.lp Problem

---

decompressed/gui_file/www/gateway-snippets/footer.lp

Gives credit not just to @Ansuel but all of the users that have ever contributed.

Link GitHub contributors list

---

decompressed/gui_file/www/docroot/login.lp

Changed globe background to lock.

---

decompressed/gui_file/www/cards/001_gateway.lp
decompressed/gui_file/www/cards/003_internet.lp
decompressed/gui_file/www/cards/009_diagnostics.lp
decompressed/gui_file/www/cards/011_usermgr.lp
decompressed/gui_file/www/cards/012_printersharing.lp
decompressed/gui_file/www/cards/015_iproutes.lp
decompressed/gui_file/www/cards/020_eco.lp
decompressed/gui_file/www/cards/091_system.lp
decompressed/gui_file/www/cards/093_xdsl.lp
decompressed/gui_file/www/lang/de-de/webui-core.po
decompressed/gui_file/www/lang/de-de/webui-printersharing.po
decompressed/gui_file/www/lang/it-it/webui-core.po
decompressed/gui_file/www/lang/it-it/webui-printersharing.po

I did not find any translations that needed tweaking but will check in dutch and Italian when I have a gateway available

/www/cards English optimisation 

---

decompressed/gui_file/www/cards/001_gateway.lp

Add TG789MYRvac v2 HP Image

---

decompressed/base/etc/init.d/rootdevice

Update rootdevice to create variant_friendly_name environment variable if it does not exist

Save variant_friendly_name

---

decompressed/gui_file/usr/share/transformer/scripts/generate-debug-file.sh

When run it will assemble data and generate a .tar.gz file containing it 
More info and file samples:
#327

DebugHelper Script

---

decompressed/gui_file/www/cards/001_gateway.lp

1. Remove leading underscore from model variable
2. Remove redundant spaces to tidy code
Variable and intermixed spaces and tabs and spaces per tab throughout all code files. How many spaces per tab?

Tidy model variable

---

decompressed/gui_file/www/cards/005_LAN.lp
decompressed/gui_file/www/cards/009_extensions.lp
decompressed/gui_file/www/docroot/modals/applications-modal.lp
decompressed/gui_file/www/docroot/modals/broadband-modal.lp
decompressed/gui_file/www/docroot/modals/contentsharing-modal.lp
decompressed/gui_file/www/docroot/modals/device-modal.lp
decompressed/gui_file/www/docroot/modals/diagnostics-connection-modal.lp
decompressed/gui_file/www/docroot/modals/diagnostics-tcpdump-modal.lp
decompressed/gui_file/www/docroot/modals/eco-modal.lp
decompressed/gui_file/www/docroot/modals/fast-cache-option-modal.lp
decompressed/gui_file/www/docroot/modals/gateway-modal.lp
decompressed/gui_file/www/docroot/modals/iproutes-modal.lp
decompressed/gui_file/www/docroot/modals/nfc-modal.lp
decompressed/gui_file/www/docroot/modals/port-mirror-modal.lp
decompressed/gui_file/www/docroot/modals/printersharing-modal.lp
decompressed/gui_file/www/docroot/modals/system-modal.lp
decompressed/gui_file/www/docroot/modals/tod_wireless-modal.lp
decompressed/gui_file/www/docroot/modals/traffic-monitor.lp
decompressed/gui_file/www/docroot/modals/wanservices-modal.lp
decompressed/gui_file/www/docroot/modals/wifi-nurse-modal.lp
decompressed/gui_file/www/docroot/modals/wireless-modal.lp
decompressed/gui_file/www/docroot/modals/wireless-qrcode-modal.lp
decompressed/gui_file/www/snippets/tabs-internet.lp
decompressed/gui_file/www/snippets/tabs-voice.lp
decompressed/gui_file/www/snippets/tabs-wireless.lp

Here is the first of 3 pull requests with english enhancements.
List [here](https://github.com/Ansuel/tch-nginx-gui/files/2812458/list.txt) for @bovirus 
Feel free to make any changes!

English Enhancements PR #1 of 3 (/www/docroot, /www/snippets and /www/cards)

---

decompressed/gui_file/www/docroot/ajax/port_status.lua

This one was tiny. No translations needed

English PR #3 of 3

---

decompressed/gui_file/www/lang/de-de/webui-core.po
decompressed/gui_file/www/lang/de-de/webui-mobiled.po
decompressed/gui_file/www/lang/it-it/webui-contentsharing.po
decompressed/gui_file/www/lang/it-it/webui-core.po
decompressed/gui_file/www/lang/it-it/webui-mobiled.po

Language updates (11.02.2019)

---

decompressed/gui_file/www/lang/de-de/webui-core.po
decompressed/gui_file/www/lang/de-de/webui-parental.po
decompressed/gui_file/www/lang/it-it/webui-core.po
decompressed/gui_file/www/lang/it-it/webui-parental.po
decompressed/gui_file/www/lang/it-it/webui-qos.po

Remove 3 double strings in webui-core.po (de - double times variable definitions)
Add strings in de/it for footer GUI info.

Update language files

---

decompressed/gui_file/www/docroot/ajax/mmpbx_status.lua
decompressed/gui_file/www/lang/it-it/webui-voice.po

Fix Telephony Info status table names

---

decompressed/gui_file/usr/share/transformer/scripts/upgradegui

See the comments for suggestions on what to add/do

Fix upgradegui english

---

README.md

Add more model numbers

---

.github/ISSUE_TEMPLATE/bug.md

To template to help debug faster
Will have to include the new modgui file

Mention Debughelper in issue templates

---

decompressed/gui_file/www/lang/de-de/webui-contentsharing.po
decompressed/gui_file/www/lang/de-de/webui-core.po
decompressed/gui_file/www/lang/it-it/webui-contentsharing.po
decompressed/gui_file/www/lang/it-it/webui-core.po

Removed a double strings in webui-core.po
Added a new string in webui-contentssharing.po

Update languages (it and de)

---

decompressed/gui_file/www/docroot/modals/system-modal.lp

Syslog Modal fixes

---

decompressed/gui_file/www/lang/it-it/webui-core.po
decompressed/gui_file/www/lang/it-it/webui-wizard.po

Update Italian language based on latest changes on source

Update Italian language

---

README.md

We have migrated the wiki so updating links

Update tg799 hacking link

---

decompressed/gui_file/www/docroot/modals/wireless-modal.lp

Allow changing of WiFi tx power

---

decompressed/gui_file/www/lang/de-de/webui-contentsharing.po
decompressed/gui_file/www/lang/de-de/webui-core.po
decompressed/gui_file/www/lang/it-it/webui-core.po

Update German language (alignment to master language table) & fix.
Update Italian language (add new string translations)

Update German aand Italian language

---

decompressed/gui_file/www/docroot/modals/device-modal.lp
decompressed/gui_file/www/lang/it-it/webui-core.po

@Ansuel 
@FrancYescO 
Please check typo fix in source code.

Fix typo + Update webuicore.po (it)

---

decompressed/gui_file/www/lang/it-it/webui-core.po

@Ansuel 
@FrancYescO 
Nuova PR aggiornamento lingua italiana

Update webui-core.po (it)

---

decompressed/gui_file/www/lang/de-de/webui-core.po

@Ansuel 
@FrancYescO 
Per favore fate il merge di quest PR per i file lingua de e it.

Update webui-core.po (de and it)

---

decompressed/gui_file/www/snippets/internet-pppoe-routed.lp

#788 
So this should bring back the IPv6 switch that is currently missing in the GUI. 
Please review prior to merge!

webui: pppoe IPv6

---

decompressed/gui_file/www/docroot/theme/dark-blue-unified/script.js

This fixes the errors on the javascript console when GUI animations setting is turned off.
Signed-off-by: Stewart Cossey <stewart.cossey@gmail.com>

Fix javascript errors with AOS object when GUI animations turned off.

---

decompressed/gui_file/www/lang/de-de/webui-core.po

bovirus asked for a few new german transaltions. Here goes...

New german translations

---

decompressed/gui_file/www/lang/it-it/webui-core.po

Fixed FEC translations

---

.github/ISSUE_TEMPLATE/bug.md

Fix debug report instructions in GitHub Bug template

Improve GitHub Bug template

---

README.md

The guide linked here is outdated, so I updated it with the new one.

Updated VANT-6 TIM guide

---

decompressed/gui_file/www/docroot/login.lp

This commit fix login button click event and 
closes https://github.com/Ansuel/tch-nginx-gui/issues/1074

Fix login button click event
